### ISSUE TITLE
Fix CI Build step

### ISSUE THREAD

**Issue by mcruzdev** [mcruzdev/platformoon-web#8]
Actually when we are running `npm run build` locally, we are receiving the following error:

```bash 
Type error: Property 'name' does not exist on type '{}'.
```

The idea here is to solve the issue and get a pipeline running well, without errors.

**Comment by avelynhc** [comment]
Hi, can I work on this?

**Comment by mcruzdev** [comment]
Hi @avelynhc surely!

**Comment by avelynhc** [comment]
@mcruzdev I dont think I can work on this. You can assign this to someone else. Sorry about that!

**Comment by mcruzdev** [comment]
Go ahead @engineerakki!

**Comment by engineerakki** [comment]
Hey @mcruzdev 
I misunderstood the issue and hence won't be able to fix it.

It is not a CI issue, 
but bug in typescript code so I will pass it on as I am not an expert in typescript

Unassigning myself.

**Comment by mcruzdev** [comment]
Hi @engineerakki no problem!

**Comment by mcruzdev** [comment]
Fixed!
